project:
  type: website

format:
  html:
    theme: solar
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:  
    logo: figs/logo.png
    background: primary
    search: true  
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]
